name: Deployment base

on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string
    secrets:

jobs:
  triage:
    runs-on: ubuntu-latest
    environment: ${{ inputs.target }}
    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.3'
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Zip application
        run: zip -r laravel-test.zip . -x ".git/*"
      - name: Move release to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: 22
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "laravel-test.zip"
          target: /data/sites/web/wiersmatestnl/subsites/dev.wiersmatest.nl
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: 22
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: cd /data/sites/web/wiersmatestnl/subsites/dev.wiersmatest.nl && unzip -o laravel-test.zip && chmod +x deploy.sh && ./deploy.sh && rm laravel-test.zip
