name: Laravel release

on:
  workflow_dispatch:

jobs:
  release:
    strategy:
      matrix:
        target: [test, staging]
    uses: dukeofharen/laravel-test/.github/workflows/deployment-base.yml@master
    with:
      target: ${{ matrix.target }}
    secrets: inherit
