name: Reusable workflow example

on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string
      testString:
        required: true
        type: string
    secrets:
      sshHost:
        required: true

jobs:
  triage:
    runs-on: ubuntu-latest
    environment: ${{ inputs.target }}
    steps:
      - name: Echo
        run: echo "Yo ${{ secrets.sshHost }} ${{ inputs.target }}"
