name: Reusable workflow example

on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string

jobs:
  triage:
    runs-on: ubuntu-latest
    environment: ${{ inputs.target }}
    steps:
      - name: Echo
        run: echo "Yo ${{ secrets.SSH_HOST }} ${{ inputs.target }} ${{ vars.TEST_STRING }}"
